### ISSUE TITLE
mage should check that all buckets disable http access

### ISSUE THREAD

**Issue by rleighton** [panther-labs/panther#1421]
### Describe the ideal solution

mage would fail the CF check if any bucket allows http access

**Comment by austinbyers** [comment]
Can you add more context? Is this high priority? Did we miss this on a new bucket? Is the check you're referring to this one:

```yml
  AnalysisVersionsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref AnalysisVersions
      PolicyDocument:
        Statement:
          - Sid: ForceSSL
            Effect: Deny
            Principal: '*'
            Action: s3:GetObject
            Resource: !Sub arn:${AWS::Partition}:s3:::${AnalysisVersions}/*
            Condition:
              Bool:
                aws:SecureTransport: false
```

It would be pretty easy to check for a "ForceSSL" statement ID with `mage` (or `cfn-lint`), but actually evaluating the policy and proving there is no http access would be harder. I'm not sure if there is a Golang equivalent of `policyuniverse`, for example
