### ISSUE TITLE
Custom logs doesn't support schemas with "similar" name

### ISSUE THREAD

**Issue by kostaspap** [panther-labs/panther#2009]
### Describe the bug

Custom logs doesn't support schemas with "similar" name. E.g. specifying two fields, `user-agent` and `user_agent` schema generation to fail

### Steps to reproduce

1. Create a new schema locally like the following:
```
version: 0
fields:
  - name: user-agent
    type: string
  - name: user_agent
    type: string
```
2. Generate a new log file with this content:
```
{"user-agent": "test", "user_agent": "test"}
```
3. Run the customlogs CLI tool

### Expected behavior

We are able to process the above fields.

### Environment

How are you deploying or using Panther?

- Panther version or commit: 1.12
