### ISSUE TITLE
Deploy fails with AWS CLI v2: Template format error

### ISSUE THREAD

**Issue by austinbyers** [panther-labs/panther#224]
### Describe the bug
When you try to deploy current master, it fails with 

```
ComplianceAPI | Template format error: YAML not well-formed. (line 786, column 24)
```

### Steps to reproduce

1. `git clone git@github.com:panther-labs/panther`
2. `mage deploy`
3. `panther-app` stack rolls back almost immediately with the error above

### Expected behavior

Deploy does not fail

### Environment

- Panther version or commit: master (`84931a`)

### Additional Context
- The actual `compliance-api` YAML template is generated by `mage` with embedded Swagger definition
- Git history shows the `compliance-api` stack hasn't been modified in over a week, so the error may not be related to that service at all

**Comment by austinbyers** [comment]
Turns out this is only an issue with the AWS CLI v2, which has only been [generally available](https://aws.amazon.com/blogs/developer/aws-cli-v2-is-now-generally-available/) for 9 days :) #136 would trivially resolve this, since then the CLI wouldn't be required to deploy Panther.

The ComplianceAPI is defined like this in the repo:

```yaml
  Function:
    Type: AWS::Serverless::Function
    Properties:
      # ... other properties ...
      FunctionName: panther-compliance-api
      Policies:
        - Id: DynamoManageItems
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:Query
                - dynamodb:*Item
                - dynamodb:Scan
              Resource:
                - !GetAtt ComplianceTable.Arn
                - !Sub
                  - '${arn}/index/*'
                  - { arn: !GetAtt ComplianceTable.Arn }  # this line turns out be interesting
```

AWS CLI v1 packages the final template like this:

```yaml
  Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: panther-compliance-api
      Policies:
      - Id: DynamoManageItems
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Action:
          - dynamodb:Query
          - dynamodb:*Item
          - dynamodb:Scan
          Resource:
          - Fn::GetAtt:
            - ComplianceTable
            - Arn
          - Fn::Sub:
            - ${arn}/index/*
            - arn:
                Fn::GetAtt:
                - ComplianceTable
                - Arn
```

AWS CLI v2 packages the final template like this:

```yaml
  Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: panther-compliance-api
      Policies:
      - Id: DynamoManageItems
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Action:
          - dynamodb:Query
          - dynamodb:*Item
          - dynamodb:Scan
          Resource:
          - Fn::GetAtt:
            - ComplianceTable
            - Arn
          - Fn::Sub:
            - ${arn}/index/*
            # !!!! CloudFormation complains about this line:
            - {arn: {Fn::GetAtt: [ComplianceTable, Arn]}}
```

The extra braces do exist in our source, so the fix may be as simple as removing them.

If no quick solution is possible, we can fallback to requiring AWS CLI v1 for now
