### ISSUE TITLE
Custom cfn resource: alarms

### ISSUE THREAD

**Issue by austinbyers** [panther-labs/panther#848]
### Description

SAR does not supported nested cfn stacks, which is how our CloudWatch alarms are currently implemented. We need to generate alarms in a SAR-compatible way.

We could publish deeply nested SAR apps for each nested alarm stack, but a cleaner solution (if it's not too much work) is to create a custom resource for each group of alarms. Then alarms can be connected directly to their associated resource. For example,

```yaml
Resources:
  MyLambdaFunction:
    Type: AWS::Serverless::Function
    # ...
     
  # Creates alarms for memory, timeout, errored invocations, logged errors, logged warnings
  MyLambdaFunctionAlarms:
    Type: Custom::LambdaAlarmGroup
    Properties:
      FunctionName: !Ref MyLambdaFunction
      # Optional
      LogWarnThreshold: 5
      LogErrorThreshold: 2
```
